### ISSUE TITLE
House names don't point to definitions (e.g. Crakehall doesn't point to House Crakehall)

### ISSUE THREAD

**Issue by melyux** [FedericoConcas/GOTdict#1]
Looking up house names (without the "House" part) is probably the most useful part of this dictionary, but it's not possible. We can add a synonym file to do this. I'll take a look at it myself.

**Comment by fedconcas** [comment]
I'm happy to see you found the dictionary useful. I can suggest a quick fix to see if it helps. 

I've done some preliminary work already but I'm missing the last step.
Can you try and pass this file
[GOTdict.txt](https://github.com/FedericoConcas/GOTdict/files/9912876/GOTdict.txt)
through this machinery?
http://languagehopper.blogspot.com/2013/06/how-to-make-your-own-stardictoldendict.html

The result should bring up a relevant entry when you select the house name. Please upload the result here if it works.

**Comment by melyux** [comment]
I went ahead and compiled the list you provided and it works well. I think it's probably better to have duplicate lines implemented as synonyms (which should be easy), so I'll see if I can do that. Here's the compiled version without the synonyms:
[GOTdict.zip](https://github.com/FedericoConcas/GOTdict/files/9993630/GOTdict.zip)

**Comment by melyux** [comment]
I've separated the duplicate lines into a .syn file. This puts all unique definitions in one place and avoids having to edit multiple lines for a single entry. I think the source code we keep on this repo should probably be the .txt file and a synonym .txt file (or CSV?), and to release, we use a build script to compile the dictionary to StarDict format. This would make the dictionary on the GitHub actually crowd-editable and abstract away the nitty-gritty compilation details.

Here's the version with the synonyms file:
[GOTdict.zip](https://github.com/FedericoConcas/GOTdict/files/9993877/GOTdict.zip)

**Comment by melyux** [comment]
This synonym thing is just the tip of the iceberg. As for other benefits, StarDict has great potential to go beyond:
- HTML tags in definition
- CSS for styling (depends on the client — KOReader is great on eInk for supporting CSS with StarDict dictionaries)
- Multiple entries for a single search term (moving away from disambiguation pages like "Willem" to simply pointing at all the different definitions for different Willems)

**Comment by fedconcas** [comment]
@melyux, your suggestion for a synonym file is based on the idea that we should change the dictionary entries.
However, this StarDict dictionary takes all the dictionary entries from the following [repository](https://github.com/wjdp/gotdict), which hasn't been updated since 2017 (fingers crossed it will be at some point when George R.R. Martin completes the new book!).
This means that the GOTdict.txt that I sent you is just a wrangled versioned of those entries, using a script I haven't published.

For this reason, I believe that changes to the dictionary should be made in the other repository, not in this conversion project.

However, I really like your suggestion of using the full potential of StarDict, so I am opening another issue.

**Comment by melyux** [comment]
I get it. But what can we improve here in that case?
